export const SKILLS = [
  { name: "JavaScript", percentage: 90, category: "Frontend" },
  { name: "TypeScript", percentage: 83, category: "Frontend" },
  { name: "React", percentage: 90, category: "Frontend" },
  { name: "Next.js", percentage: 90, category: "Frontend" },
  { name: "Zustand", percentage: 90, category: "Store" },
  { name: "Recoil", percentage: 90, category: "Store" },
  { name: "Redux", percentage: 90, category: "Store" },
  { name: "Tailwind CSS", percentage: 90, category: "Style" },
  { name: "Styled Components", percentage: 90, category: "Style" },
  { name: "SCSS", percentage: 83, category: "Style" },
  { name: "Git", percentage: 90, category: "Tools" },
  { name: "Figma", percentage: 83, category: "Tools" },
  { name: "Claude", percentage: 90, category: "AI" },
  { name: "Cursor", percentage: 83, category: "AI" },
  { name: "n8n", percentage: 83, category: "AI" },
] as const;
