export const ROBOT_CHAT_NAVIGATION_2LAYER_ARCHITECTURE_MARKDOWN = [
  `전시·데모 환경에서 로봇 UI를 운영하다 보면 “대화(LLM/음성)”와 “이동(goTo/도착/실패)”이 한 화면에서 자연스럽게 연결돼야 합니다. 하지만 구현이 한 상태 트리, 한 훅, 한 화면에 얽히기 시작하면 정책 변경이 눈덩이처럼 커지고, 이동 실패/도착 UX가 상황마다 들쭉날쭉해지기 쉽습니다.`,
  `이번 글은 그 문제를 **요구사항 기반으로 구조로 고정**한 기록입니다. 결론부터 말하면 **대화 도메인과 이동 도메인을 분리하고(selector로 파생), 이동 명령·브릿지 이벤트·메시지 정책을 “상위에서만” 조합**하는 2-Layer 구조로 정리했습니다.`,
  `> 한 줄 요약
  
  > 대화(chat)와 이동(robot)을 도메인으로 분리하고, 파생 조건은 selector로 단일화한 뒤, 이동 디스패치·도착/오류 이벤트·이동 UI를 상위 훅에서만 조합하도록 고정했습니다.`,
  `---`,
  `## 1) 문제 정의: 왜 구조가 먼저였는지`,
  `<br/>`,
  `현장에서 실제로 터지는 문제는 기능 하나의 버그가 아니라, **도메인 결합이 만든 변경 비용**이었습니다.`,
  `첫째, 대화 흐름과 이동 흐름이 한 화면/한 상태에서 섞이면 이동 정책을 바꾸는 순간 대화 UI까지 파급됩니다. 예를 들어 재시도 횟수, 실패 메시지 톤, 도착 후 전환(모달, 타이머, 홈 복귀) 같은 운영 정책이 바뀔 때마다 손대야 하는 범위가 커집니다.`,
  `둘째, 이동 중 안내·장애물로 인한 goTo 실패·도착 후 전환이 각기 다른 UI와 메시지 경로에 흩어지면 사용자 경험이 불일치해집니다. 텍스트·TTS·닫기 정책이 상황마다 달라지고, 운영 중 문구 변경도 “어디를 고쳐야 하는지”부터 다시 찾게 됩니다.`,
  `셋째, 로봇 이벤트는 비동기·외부 입력입니다. \`window.onArrival\`, \`window.onError\`, \`AndroidBridge.goTo\` 같은 브릿지 이벤트가 UI 상태와 섞이면 경합이 쉽게 발생합니다. 중복 이동, 잘못된 상태 전이, 이벤트 처리 순서에 따른 흔들림이 전형적인 리스크였습니다.`,
  `그래서 이번 작업은 “버그를 한 번 고치는” 것이 아니라, **운영 변경이 반복되는 환경에서 바꿀 지점을 좁히는 구조**를 만드는 것이 핵심이었습니다.`,
  `---`,
  `## 2) 요구사항: 설계를 결정한 제약 조건`,
  `<br/>`,
  `요구사항은 구현 디테일이 아니라 “구조가 지켜야 하는 약속”으로 정리했습니다.`,
  `- **R1. 대화/이동 책임 분리(2-Layer)**: 대화 상태/타입과 이동 상태/타입은 도메인별로 분리하고, UI는 상위에서만 조합 가능해야 합니다.`,
  `- **R2. 파생 상태는 selector로 단일화**: \`isMoving\`, \`isSora\`, \`isAbleFetchLocationInfo\` 같은 표시/동작 조건은 selector로만 파생하고, 컴포넌트/훅에서 조건문을 중복 생산하지 않습니다.`,
  `- **R3. 이동 명령은 단일 엔트리포인트**: 이동 시작은 \`dispatchMove\` 같은 단일 API로만 수행하며, 중복 이동 방지·시연 중 이동 금지 같은 가드는 한 곳에 모읍니다.`,
  `- **R4. 공통 메시지/이동 UI 통합**: 이동 중 안내, 실패(재시도/포기), 도착 후 전환은 하나의 UI(예: \`MovingModal\`)로 일관되게 표현하고, 기본 이동 문구는 중앙 생성기에서 관리합니다.`,
  `- **R5. 브릿지 이벤트 처리의 중앙 집중**: \`onArrival\`, \`onError(GOTO)\`는 상위 훅에서만 처리하고, 도착/실패 후처리(대화 초기화, 모달 close 등)를 일관되게 보장합니다.`,
  `- **R6. 운영 변경 최소 수정**: 메시지/플로우 정책 변경 시 수정 범위가 “메시지 생성기 또는 이벤트 핸들러/모달”로 제한돼야 합니다.`,
  `---`,
  `## 3) 설계 의도와 의사결정 근거`,
  `<br/>`,
  `### 3-1. 도메인 경계를 코드 구조로 강제했습니다`,
  `대화는 \`chat/*\`, 이동/로봇은 \`robot/*\`로 **상태·타입·파생값을 분리**했습니다. 이렇게 하면 대화 기능을 개선할 때 이동 정책을 모르고도 작업할 수 있고, 반대로 이동 정책을 바꿔도 대화 UI가 깨지지 않게 됩니다.`,
  `### 3-2. UI는 계산이 아니라 표현에 집중하도록 만들었습니다`,
  `컴포넌트에서 \`robotState === 'MOVING'\` 같은 원시 조건을 직접 계산하는 순간, “정책”이 UI 파일 곳곳으로 새어 나갑니다. 대신 selector가 \`isMoving\` 같은 **의미 있는 값**을 만들고, UI는 그 값을 소비하는 구조로 고정했습니다.`,
  `### 3-3. 이동 UX를 ‘하나의 언어’로 통일했습니다`,
  `이동 중/실패/안내가 서로 다른 컴포넌트로 분산되면 텍스트·TTS·닫기 정책이 달라집니다. 그래서 \`MovingModal\` + \`createMovingMessage\`로 이동 메시지를 **중앙에서 통제**했습니다. 운영 중 문구나 톤을 바꾸더라도 수정 범위가 줄어듭니다.`,
  `### 3-4. 브릿지 비동기를 제어 가능한 이벤트로 흡수했습니다`,
  `전역 이벤트는 “누가 처리하나”가 불명확해지기 쉽습니다. 그래서 \`onArrival\`/ \`onError\`는 상위 훅이 책임지고, UI/스토어는 외부 입력에 직접 흔들리지 않게 했습니다.`,
  `---`,
  `## 4) 구현 근거: 레포에서 확인할 수 있는 ‘구조의 증거’`,
  `<br/>`,
  `아래는 “문장”이 아니라 실제 코드에서 그 구조가 어떻게 강제되는지의 근거입니다.`,
  `### 4-1. 대화(Conversation) 도메인 분리`,
  `<br/>`,
  `대화 히스토리는 \`src/store/chat/chatAtoms.ts\`의 atom으로 관리됩니다. UI에 필요한 값(히스토리 존재, 마지막 메시지)은 \`src/store/chat/chatSelectors.ts\`에서 selector로 파생합니다. 타입은 \`src/types/chat.d.ts\`에 별도로 둬서 도메인 타입 경계를 유지합니다.`,
  `\`\`\`ts\n// src/store/chat/chatAtoms.ts\nexport const chatHistoryState = atom<ChatHistoryInfo>({\n  key: "chatHistory",\n  default: { history: [] },\n});\n\`\`\``,
  `\`\`\`ts\n// src/store/chat/chatSelectors.ts\nexport const chatStatusSelector = selector({\n  key: "chatStatus",\n  get: ({ get }) => {\n    const chatHistory = get(chatHistoryState);\n    return {\n      isExistChatHistory: chatHistory && chatHistory.history.length > 0,\n      lastChatMessage:\n        chatHistory && chatHistory.history[chatHistory.history.length - 1],\n    };\n  },\n});\n\`\`\``,
  `### 4-2. 이동/로봇(Navigation/Robot) 도메인 분리 + selector 기반 파생`,
  `<br/>`,
  `로봇 상태 머신 타입은 \`src/types/robot.d.ts\`에 분리되어 있고, “UI 상태/동작 조건”은 \`src/store/robot/robotSelectors.ts\`에서 selector로 파생됩니다. 여기서 \`isMoving\`, \`isSora\`, \`isAbleFetchLocationInfo\` 같은 조건이 한 곳에서 결정됩니다.`,
  `\`\`\`ts\n// src/types/robot.d.ts\ntype RobotState =\n  | \"WELCOME\"\n  | \"IDLE\"\n  | \"MOVING\"\n  | \"STANDBY\"\n  | \"HOME\"\n  | \"HOME_BASE\"\n  | \"TOUR\"\n  | \"SORA\";\n\`\`\``,
  `\`\`\`ts\n// src/store/robot/robotSelectors.ts\nexport const robotMovementStatusSelector = selector({\n  key: \"robotMovementStatus\",\n  get: ({ get }) => {\n    const robotStateState = get(robotStateAtom);\n    const currentLocation = get(selectedRobotLocationState);\n    const homeName = get(robotHomeNameState);\n    return {\n      isGoToLocation:\n        currentLocation !== null &&\n        currentLocation !== homeName &&\n        robotStateState === \"MOVING\",\n      isGoToHome: homeName === currentLocation && robotStateState === \"HOME\",\n      isGoToHomeBase: robotStateState === \"HOME_BASE\",\n      isTour: robotStateState === \"TOUR\",\n      isFirstBoot: robotStateState === \"WELCOME\",\n      isMoving: robotStateState === \"MOVING\",\n      isSora: robotStateState === \"SORA\",\n    };\n  },\n});\n\`\`\``,
  `\`\`\`ts\n// src/store/robot/robotSelectors.ts\nexport const robotLocationStatusSelector = selector({\n  key: \"robotLocationStatus\",\n  get: ({ get }) => {\n    const robotStateState = get(robotStateAtom);\n    return {\n      isAbleFetchLocationInfo:\n        robotStateState !== \"TOUR\" &&\n        robotStateState !== \"HOME_BASE\" &&\n        robotStateState !== \"HOME\" &&\n        robotStateState !== \"WELCOME\",\n    };\n  },\n});\n\`\`\``,
  `### 4-3. 이동 명령 단일화: dispatchMove 한 곳에 가드 집중`,
  `<br/>`,
  `이동 시작은 \`src/hooks/useRobotMoveDispatcher.ts\`의 \`dispatchMove\`에서만 수행되며, 중복 이동(\`isMoving\`)과 시연 중 이동 금지(\`isSora\`) 가드가 한 곳에 모여 있습니다. 이 구조 덕분에 goTo 호출 지점을 늘려도 정책 누락이 줄어듭니다.`,
  `\`\`\`ts\n// src/hooks/useRobotMoveDispatcher.ts\nexport function useRobotMoveDispatcher() {\n  const [robotState, setRobotState] = useRecoilState(robotStateAtom);\n  const setSelectedLocation = useSetRecoilState(selectedRobotLocationState);\n  const robotMovementStatus = useRecoilValue(robotMovementStatusSelector);\n  const resetUserSpeechState = useSetRecoilState(resetUserSpeechActionSelector);\n\n  const dispatchMove = useCallback(\n    (location: string, source: \"carousel\" | \"llm\" | \"other\") => {\n      if (!location) return;\n      if (robotMovementStatus.isMoving) return;\n      if (robotMovementStatus.isSora) return;\n\n      resetUserSpeechState(null);\n\n      if (location === \"홈\") setRobotState(\"HOME\");\n      else if (location === \"home base\") setRobotState(\"HOME_BASE\");\n      else setRobotState(\"MOVING\");\n\n      setTimeout(() => {\n        if (window.AndroidBridge?.goTo) {\n          window.AndroidBridge.goTo(\n            location.toLowerCase(),\n            false,\n            false,\n            false,\n            false,\n            \"MEDIUM\",\n          );\n          setSelectedLocation(location.toLowerCase());\n        }\n      }, 0);\n    },\n    [robotMovementStatus.isMoving],\n  );\n\n  return { dispatchMove };\n}\n\`\`\``,
  `### 4-4. 공통 메시지 중앙 관리 + 이동 UI 통합(MovingModal)`,
  `<br/>`,
  `기본 이동 안내 문구는 \`src/utils/common-helper.tsx\`의 \`createMovingMessage\`에서 생성합니다. \`MovingModal\`은 \`customMessage\`가 있으면 그 문구를, 없으면 중앙 생성기 결과를 노출합니다. 즉, 이동 문구 정책이 흩어지지 않고 한 곳에서 바뀝니다.`,
  `\`\`\`ts\n// src/utils/common-helper.tsx\nexport const createMovingMessage = (\n  location: string | null,\n  language: \"ko\" | \"en\" = \"ko\",\n): string => {\n  if (!location) return \"\";\n\n  if (language === \"en\") {\n    if (location === \"home base\") {\n      return \"Robot is currently moving to the charging station\";\n    }\n    return \"Robot is currently moving to \" + location;\n  }\n\n  if (location === \"home base\") {\n    return \"로봇이 현재 충전기로 이동중입니다\";\n  }\n\n  const particle = getKoreanParticle(location);\n  return \"로봇이 현재 \" + location + particle + \" 이동중입니다\";\n};\n\`\`\``,
  `\`\`\`tsx\n// src/components/modal/MovingModal.tsx\nconst getDisplayTitle = () => {\n  if (customMessage) return customMessage;\n  return createMovingMessage(movingLocation || \"\", i18n.language as \"ko\" | \"en\");\n};\n\`\`\``,
  `### 4-5. onError(GOTO): 실패 플로우도 동일 UI로 흡수`,
  `<br/>`,
  `\`src/hooks/useOnError.ts\`에서 GOTO 계열 오류를 받아, 재시도/포기 메시지를 모두 \`MovingModal\` 하나로 안내합니다. “실패 메시지 톤”이 흩어지지 않고, 운영 정책(재시도 횟수, 메인 복귀 타이밍)을 한 곳에서 바꾸기 쉬워집니다.`,
  `\`\`\`ts\n// src/hooks/useOnError.ts\nwindow.onError = (code: string, message: string) => {\n  if (code.startsWith(\"GOTO\")) {\n    closeAllModals();\n\n    if (selectedLocation && retryCount < MAX_RETRY_COUNT) {\n      const text = \"조금만 비켜주세요. 에이든이 이동중입니다.\";\n      movingModal.open({ customMessage: text, errorCode: { code, message } });\n      dispatchMove(selectedLocation, \"other\");\n      setRobotState(\"IDLE\");\n      return;\n    }\n\n    const text = \"다음 공간 이동을 하지 못하였습니다. 메인화면으로 이동하겠습니다.\";\n    movingModal.open({ customMessage: text, errorCode: { code, message } });\n    setChatHistoryState((prev) => ({ ...prev, history: [] }));\n    setRetryCount(0);\n    setRobotState(\"IDLE\");\n    setTimeout(() => closeAllModals(), 8000);\n  }\n};\n\`\`\``,
  `### 4-6. onArrival: 도착 처리도 상위 훅에서 중앙 집중`,
  `<br/>`,
  `\`src/hooks/useRobotArrivalHandler.ts\`에서 도착 이벤트를 처리하고, 대화 초기화, 이동 모달 close, 상태 전이를 한 곳에서 보장합니다. 특히 “외부 이벤트 처리와 UI 상태가 섞이면 흔들린다”는 문제를, 상위 훅으로 책임을 고정하는 방식으로 줄였습니다.`,
  `\`\`\`ts\n// src/hooks/useRobotArrivalHandler.ts\nwindow.onArrival = (location: string, pos: any) => {\n  if (robotMovementStatus.isSora) return;\n\n  setRetryCount(0);\n\n  if (location === selectedLocation && robotLocationStatus.isAbleFetchLocationInfo) {\n    setTimeout(() => fetchLocationInfo(location), 0);\n  }\n\n  resetUserSpeechState(null);\n  setChatHistoryState((prev) => ({ ...prev, history: [] }));\n\n  if (homeName && location === homeName) {\n    setTimeout(() => {\n      setRobotState(\"HOME\");\n      movingModal.close();\n      if (onIdleArrive) onIdleArrive();\n    }, 0);\n    return;\n  }\n\n  if (location === \"home base\") {\n    setTimeout(() => {\n      setRobotState(\"HOME_BASE\");\n      movingModal.close();\n    }, 0);\n    return;\n  }\n\n  if (location === \"시연홈\") {\n    setTimeout(() => {\n      setRobotState(\"SORA\");\n      delegatedModal.open();\n      movingModal.close();\n    }, 0);\n    return;\n  }\n\n  if (robotMovementStatus.isTour) return;\n\n  setTimeout(() => {\n    setRobotState(\"IDLE\");\n    if (onIdleArrive) onIdleArrive();\n  }, 0);\n};\n\`\`\``,
  `### 4-7. 상위 컨테이너에서만 대화/이동 UI를 조합했습니다`,
  `<br/>`,
  `\`src/containers/NewGuideWrap.tsx\`에서는 목적지 변경을 감지해 이동 모달을 열고, 도착 처리를 훅으로 위임합니다. 이 지점이 2-Layer 조합점이 됩니다.`,
  `\`\`\`tsx\n// src/containers/NewGuideWrap.tsx\nuseRobotArrivalHandler({\n  onIdleArrive: () => {\n    resetAndStartIdleTimer();\n  },\n});\n\nuseEffect(() => {\n  if (selectedLocation) {\n    movingModal.open();\n  }\n}, [selectedLocation]);\n\`\`\``,
  `---`,
  `## 5) 결과: 운영 변경의 ‘수정 범위’를 줄였습니다`,
  `<br/>`,
  `이 구조의 효과는 “코드가 예뻐졌다”가 아니라, 운영 요구가 들어올 때 어디를 고치면 되는지가 명확해졌다는 데 있습니다.`,
  `- 이동 문구/톤을 바꾸려면 \`createMovingMessage\` 또는 \`MovingModal\`에만 손대면 됩니다.`,
  `- 재시도/포기 정책을 바꾸려면 \`useOnError\`의 GOTO 분기만 보면 됩니다.`,
  `- 도착 후 전환 정책(홈/충전기/시연홈)을 바꾸려면 \`useRobotArrivalHandler\`만 보면 됩니다.`,
  `- 화면은 selector가 만든 의미값을 표시하는 데 집중하므로, UI 파일에서 정책 조건이 중복되지 않습니다.`,
  `---`,
  `## 마치며`,
  `전시·데모는 “정답의 제품”이라기보다 “계속 바뀌는 운영”에 가깝습니다. 그래서 요구사항을 먼저 세우고, 도메인 경계를 구조로 고정해 **바꿀 지점을 좁히는 설계**가 더 중요하다고 느꼈습니다. 다음 작업은 selector/훅 경계를 유지한 채로 정책을 데이터화(예: 재시도 정책 테이블)해 운영 변경을 더 안전하게 만드는 방향을 검토할 예정입니다.`,
].join("\n\n");
